### ISSUE TITLE
GPU util stuck at 0%?

### ISSUE THREAD

**Issue by jfainberg** [anderskm/gputil#11]
I'm having a strange issue on various machine where every call of showUtilization() shows 0% GPU util, even though nvidia-smi at the same time returns 100%. It does, however, correctly show memory usage. Any idea why this might occur?

Thanks for writing this utility!

**Comment by anderskm** [comment]
@jfainberg Thank you for using GPUtil :-)

The two ought to show the same.
Your issue sounds odd, but I cannot rule out, that there might exist an error in the code.
To debug the issue, could you please post the raw outputs produced by `showUtilization(all=True)`, by `nvidia-smi` without any additional arguments and by `nvidia-smi` using when using the following arguments:
```
nvidia-smi --query-gpu=index,uuid,utilization.gpu,memory.total,memory.used,memory.free,driver_version,name,gpu_serial,display_active,display_mode --format=csv,noheader,nounits
```
It is the same arguments, GPUtil uses when calling nvidia-smi.

**Comment by jfainberg** [comment]
Thanks for your reply!:) They seem to match!

I wonder if it's because I try to use it to show GPU usage during training of a model (in the same script), and I'm not doing both at the same time: e.g. it calls showUtilization for a split second when the GPU isn't being used (although it keeps memory since my variables haven't been overwritten yet). I need to find a way around that...

**Comment by jfainberg** [comment]
Yes indeed! I set it up in a separate monitoring thread and it works as expected. Apologies for this! Happy to submit an example for the readme if you'd like (up to you :-) ).

**Comment by kevinashaw** [comment]
This looks like a great library.  However, I too have the same problem.  I'm trying to use GPUtil to monitor GPU usage for Tensorflow during execution.  I too am getting only zeros.  I've read the comments above and am not clear why this would be the case.  If infact we need multithreaded code to use this, it might be helpful to let people know.  And to provide some sample code.  Just a thought.

**Comment by anderskm** [comment]
@kevinashaw I had not considered continuous monitoring as a case, when I created GPUtil, but I realise now, that it is desired.
Luckily, @jfainberg has submitted an example for performing continuous monitoring using a monitor thread.

I'm closing this issue, as it has been handled with example code provided by @jfainberg.

**Comment by kevinashaw** [comment]
I'm not sure that I view it as "continuous" monitoring.  I have an TensorFlow training session and want to confirm GPU utilization (mostly looking for stalls, when the GPU hangs).  During training, at regulary intervals, the test data is checked for accuracy, at this point I also check the GPU utilization and log it to a dashboard.  My issue was that when I do this, I find a "0%" utilization from GPUtil.  
Does this still fit your use-case?
Thanks.

**Comment by anderskm** [comment]
@kevinashaw I think you should be able to do that with the example provided by @jfainberg . Just start the monitoring thread, when you start evaluating your test data and stop it again afterwards. That should print the utilization in your terminal window.
If you want to store the utilization in a tensorflow summary, then you will have to grab the utilization from the monitoring thread. As you will only be reading from your main thread, you might be able to get away with using global variables. See [https://stackoverflow.com/a/19790803](https://stackoverflow.com/a/19790803)
Cheers

**Comment by kevinashaw** [comment]
Great.  Thanks!

Kevin Shaw
kevinashaw@gmail.com
